name: Fetch JSON and save to repo

on:
  schedule:
    - cron: '*/90 * * * *' # This will trigger the workflow every 2 minutes

jobs:
  fetch_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch JSON and save to repo
      run: |
        python -c "import requests; response = requests.get('https://script.googleusercontent.com/macros/echo?user_content_key=XACeE8MoN8-uCJyFBlVxmgVKVcUQt0w1zyblwBhENYZydYpp2uK7nBMvxQMj17KWuQxbXJn6socaTeZWgI8tbtTQXtsiSLbPm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnMWUhDeXdxvnTaM02i16QTJiz7Ionwk5oDyy30Cpk6ULUp5XEMu3d-EfAtpV1hEvW2mkRPmIxNCQiPtSi8q8b59uJAXjZolx3g&lib=MA6F-UP0pNkZntVp7DtTRzwGgahm_W7Lh'); open('data.json', 'w').write(response.text)"

    - name: Commit and push changes
      run: |
        git config --global user.email "daga.git@gmail.com"
        git config --global user.name "dagaa"
        git add data.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update data.json" && git push
